name:                brainfuck-interpreter-gui
version:             0.1.0.0

data-files:
- ./test/*.bf

dependencies:
- base
- binary
- containers
- silently
- gi-gtk
- freetype2
- cairo
- haskell-gi-base
- text

library:
  source-dirs: src
  exposed-modules:
  - Lib
  - GUITest

executables:
  brainfuck-interpreter-gui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainfuck-interpreter-gui

tests:
  brainfuck-interpreter-gui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainfuck-interpreter-gui
    - tasty
    - tasty-hunit
