resolver: lts-22.31
compiler-check: newer-minor

packages:
- .

# Get nix (package manager, not distro) from https://nixos.org/download/
nix:
  enable: true
  packages:
    - pkg-config
    - glib
    - gobject-introspection
    - pcre2
    - freetype
    - cairo
    - expat
    - fontconfig
    - util-linux
    - harfbuzz
    - libselinux
    - libsepol
    - xorg.libXdmcp
    - gtk3
    - lerc
    - libthai
    - libdatrie
    - libxkbcommon
    - libepoxy
    - xorg.libXtst
    - libsysprof-capture
